services:
  frontend:
    build:
      context: .
      dockerfile_inline: |
        FROM node:22-alpine as build-stage
        WORKDIR /app
        COPY frontend /app
        RUN npm run build

        FROM nginx as deployment
        COPY --from=build-stage /app/dist /app
        COPY frontend/nginx.conf /etc/nginx/nginx.conf
    restart: unless-stopped
    ports:
      - 8080:80

  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile_inline: |
        FROM python:3.12-bookworm
        RUN apt update && \
            pip install -U pip && \
            pip install fastapi uvicorn[standard] sqlalchemy psycopg2 && \
            useradd --shell /bin/bash --create-home book-api-user
        USER book-api-user
        WORKDIR /app
        COPY --chown=book-api-user .env runBackend.py /app
        COPY --chown=book-api-user backend/*.py /app/backend/
        COPY --chown=book-api-user backend/router/*.py /app/backend/router/
        EXPOSE 8530
        CMD ["python", "runBackend.py"]
    depends_on:
      - database
    restart: unless-stopped
    ports:
      - 8081:8530

volumes:
  db-data:
